enum {
    ID_VERSION_INFO = 1,

    ID_NEW_GAME,
    ID_NEW_PERIOD,

    ID_CLOCK_TIMER,
    ID_BUZZER_TIMER,

    ID_TOGGLE_TIME,
    ID_START_TIME,
    ID_STOP_TIME,
    ID_TOGGLE_SHOT_CLOCK,
    ID_START_SHOT_CLOCK,
    ID_RESET_SHOT_CLOCK,

    ID_INC_LEFT_SCORE,
    ID_DEC_LEFT_SCORE,

    ID_INC_RIGHT_SCORE,
    ID_DEC_RIGHT_SCORE,

    ID_INC_LEFT_FOUL,
    ID_DEC_LEFT_FOUL,

    ID_INC_RIGHT_FOUL,
    ID_DEC_RIGHT_FOUL,

    ID_INC_PERIOD,
    ID_DEC_PERIOD,

    ID_PERIOD_LENGTH_TEXT,
    ID_SHOT_CLOCK_TEXT,
};
